version: "3"

services:
  resource:
    image: carlosvj/fablat:fablat-resource
    ports:
      - "9000:9000"
  ui:
    image: carlosvj/fablat:fablat-ui
    ports:
      - "80:8080"
    links:
      - resource